### PR TITLE
Make `InsertTupleIntoChunk` more efficient

### PR DESCRIPTION
**Pull request by Reminiscent**
Fix https://github.com/duckdb/pg_duckdb/issues/402

1. Cache the detoast variables if they are both part of a filter and one of the output variables.
2. Only contain the values that we actually need to output in the value.

### CODE REVIEW

**Comment by Reminiscent** [comment]
I have two questions:
1. Are there any easy way to add a bench test to show the improvement? Or we just add some complex test cases in the regression test and see the result.
2. Now we still use `vector` for the `values` array, we can replace it to the map. But such a change may not be necessary, and it's unclear how much of an improvement it would bring.

**Review by JelteF — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing this. I left a few comments. Maybe don't spend time on implementing them yet though, because we're currently working on a big change to the reading and filtering. So it's a possibility that we actually end up removing this code.

**Comment by JelteF** [comment]
Okay, so chances are very high that we'll remove this code completely in 0.3.0. So I don't think it makes sense to continue with this approach. Thanks anyway for your efforts.

**Comment by JelteF** [comment]
For reference #477 is the PR that removes this code.

**Pull request closed without merging**
