### PR TITLE
Handles exceptions when using the "explain verbose" statement

### LINKED ISSUE #465: Stack depth limit exceeded when using explain verbose
### What happens?

Stack depth limit exceeded when using explain verbose
0245ee83d25c14791802b4c096b4c38

### To Reproduce

```plpgsql
SET duckdb.force_execution = true;
CREATE TABLE ta(a INT);
EXPLAIN VERBOSE SELECT * FROM ta;
``` 

### OS:

centos8

### pg_duckdb Version (if built from source use commit hash):

main

### Postgres Version (if built from source use commit hash):

16.6

### Hardware:

_No response_

### Full Name:

Man Zeng

### Affiliation:

Halo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Leo-XM-Zeng**
Fixes #465

### CODE REVIEW

**Review by JelteF — COMMENTED** [review]
This is not how this should be fixed. Basically this now disables `EXPLAIN VERBOSE` flag completely to hide the bug. That might be acceptable for a first iteration, except for the fact that this disables EXPLAIN VERBOSE even for queries that don't use DuckDB. I opened #468 now to fix this issue in a better way. I also change the tests to be part of our existing explain tests.

**Comment by Leo-XM-Zeng** [comment]
> This is not how this should be fixed. Basically this now disables `EXPLAIN VERBOSE` flag completely to hide the bug. That might be acceptable for a first iteration, except for the fact that this disables EXPLAIN VERBOSE even for queries that don't use DuckDB. I opened #468 now to fix this issue in a better way. I also change the tests to be part of our existing explain tests.

oh, I looked at your approach and it was more appropriate, I just took into account that duckdb does not support "explain verbose" and that all the operations on "explain" are performed in duckdb, not PG.

**Comment by JelteF** [comment]
To be clear: thanks a lot for the bug report and the initial attempt at a fix.

**Comment by Leo-XM-Zeng** [comment]
> To be clear: thanks a lot for the bug report and the initial attempt at a fix.

Thank you for your encouragement and guidance. haha~

**Pull request closed without merging**
